ToDoApp/urls.py
from django.urls import path
from . import views

app_name = "ToDoApp"

urlpatterns = [
    path("", views.index, name="index"),
    path("month/<int:month>/", views.ausgaben, name="ausgaben"),
]

ToDoWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ToDoApp.urls"))
]

ToDoApp/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Ausgaben(models.Model):
    TYPE = (
        ('E', 'Einnahmen'),
        ('A', 'Ausgaben')
    )
    MONTHS = (
        (1, 'Januar'),
        (2, 'Februar'),
        (3, 'März'),
        (4, 'April'),
        (5, 'Mai'),
        (6, 'Juni'),
        (7, 'Juli'),
        (8, 'August'),
        (9, 'September'),
        (10, 'Oktober'),
        (11, 'November'),
        (12, 'Dezember'),
    )

    CATEGORYS = (
        ('W', 'Wohnen'),
        ('L', 'Leben'),
        ('H/F', 'Hobby/Freizeit'),
        ('M', 'Mobilität'),
        ('B', 'Bildung'),
        ('S/I', 'Sparen/Investieren'),
        ('S', 'Sonstiges')
    )

    type = models.CharField(
        max_length=1,
        choices=TYPE,
        default='A',
        help_text="Einnahme oder Ausgabe."
    )
    month = models.IntegerField(
        choices=MONTHS,
        default=MONTHS[datetime.now().month-1],
        help_text="Monat der Ausgabe."
    )
    category = models.CharField(
        max_length=10,
        choices=CATEGORYS,
        help_text="Kategorie der Ausgabe."
    )
    title = models.CharField(max_length=30, help_text="Bezeichnung der Ausgabe.")
    amount = models.DecimalField(max_digits=10, decimal_places=2, help_text="Betrag der Ausgabe.")


    def __str__(self):
        return f"{self.type}-{self.title}: {self.amount}"

ToDoApp/forms.py
from django import forms
from ToDoApp.models import Ausgaben


class AusgabenForm(forms.ModelForm):
    class Meta:
        model = Ausgaben
        fields = '__all__' 

ToDoApp/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from .models import Ausgaben
from django.urls import reverse
from .forms import AusgabenForm
from bokeh.plotting import figure
from bokeh.embed import components
from bokeh.models import ColumnDataSource, FactorRange
from bokeh.transform import factor_cmap
from bokeh.palettes import Spectral5

# Create your views here.
def ausgaben(request, month):
    alleAusgaben = Ausgaben.objects.all()
    ausgabenMonth = alleAusgaben.filter(month=month)
    context = {}
    context["monat"] = month
    context["ausgaben"] = ausgabenMonth
    form = AusgabenForm(initial={"month": month})

    if request.method == 'POST':
        if 'save' in request.POST:
            pk = request.POST.get('save')
            if not pk:
                form = AusgabenForm(request.POST)
            else:
                ausgabe = Ausgaben.objects.get(id=pk)
                form = AusgabenForm(request.POST, instance=ausgabe)
            form.save()
            form = AusgabenForm(initial={"month": month})
        elif 'edit' in request.POST:
            pk = request.POST.get('edit')
            ausgabe = Ausgaben.objects.get(id=pk)
            form = AusgabenForm(instance=ausgabe)

        elif 'delete' in request.POST:
            pk = request.POST.get('delete')
            ausgabe = Ausgaben.objects.get(id=pk)
            ausgabe.delete()

    context["form"] = form
    return render(request, "ausgaben.html", context)


def index(request):
    items = Ausgaben.objects
    einnahmen = []
    ausgaben = []
    for x in range(1,13):
        monat = items.filter(month=x) 
        Ein = [eintrag.amount for eintrag in monat.filter(type='E')]
        einnahmen.append(float(sum(Ein))) 
        Aus = [eintrag.amount for eintrag in monat.filter(type='A')]
        ausgaben.append(float(sum(Aus))) 
    months = ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni',
              'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember']
    type = ['E', 'A']
    data = {'months': months,
            'E': einnahmen,
            'A': ausgaben}
    palette = ('#00FF00', '#FF0000')

    x = [(m, t) for m in months for t in type]
    counts = sum(zip(data['E'], data['A']), ())
    source = ColumnDataSource(data=dict(x=x, counts=counts))
    plot = figure(x_range=FactorRange(*x), width=1200, height=500,
                  title="Jahresübersicht Einnahmen/Ausgaben",
                  toolbar_location=None, tools="")
    plot.vbar(x='x', top='counts', width=0.9, source=source,
              fill_color=factor_cmap('x', palette=palette, factors=type, start=1, end=2))
    script, div = components(plot)

    context = {}
    context["script"] = script
    context["div"] = div   

    return render(request, "home.html", context)

ToDoApp/templates/ausgaben.html
{% extends "base.html" %} 
{% block title %} Finanzen-Tracker {% endblock %}
{% block home %}
<a href="{% url 'ToDoApp:index' %}">Home</a>
{% endblock %}
{% block content %}
<form method="POST" action="{% url 'ToDoApp:ausgaben' monat %}">
{% csrf_token %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Typ</th>
                <th>Monat</th>
                <th>Kategorie</th>
                <th>Titel</th>
                <th>Betrag in Euro</th>
                <th>Aktion</th>
            </tr>
        </thead>
        <tbody>
            {% if not form.instance.id %}
            <tr>
                {%include 'save.html'%}
            </tr>
            {% endif %}
            {% for ausgabe in ausgaben %}
            <tr class="{% if ausgabe.type == 'A' %}table-danger{% elif ausgabe.type == 'E' %}table-success{% endif %}">
                {% if form.instance.id == ausgabe.id %}
                {% include 'save.html' %}
                {% else %}
                <td>{{ausgabe.get_type_display}}</td>
                <td>{{ausgabe.get_month_display}}</td>
                <td>{{ausgabe.get_category_display}}</td>
                <td>{{ausgabe.title}}</td>
                <td>{{ausgabe.amount}}</td>
                <td>
                    <button formnovalidate type="submit" class="btn btn-warning" name="edit" value="{{ausgabe.id}}">Bearbeiten</button>
                    <button formnovalidate type="submit" class="btn btn-danger" name="delete" value="{{ausgabe.id}}">Löschen</button>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</form>
{% endblock %}

ToDoApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %} Django App {% endblock %}</title>
        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

        <!-- Bokeh -->
        <link href="http://cdn.pydata.org/bokeh/release/bokeh-3.6.3.min.css" rel="stylesheet" type="text/css">
        <link href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-3.6.3.min.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <header class="container d-flex flex-direction-row align-items-center justify-content-around">
            <h1>Finanzen-Tracker {% block monat %}{% endblock %}</h1>
            {% block home %}{% endblock %}
        </header>

        <div class="container">
            {% block content %} {% endblock %}
        </div>
        
        <div class="container">
            {% block footer %} {% endblock %}
        </div>

        <!-- Bootstrap -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

        <!-- Bokeh -->
        <script src="https://cdn.bokeh.org/bokeh/release/bokeh-3.6.3.min.js"></script>
        <script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.6.3.min.js"></script>
        <script src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.6.3.min.js"></script>
        <script src="https://cdn.bokeh.org/bokeh/release/bokeh-api-3.6.3.min.js"></script>

        <!-- Personal -->
        <script src="{% static 'ToDoApp/main.js' %}"></script>

    </body>
</html>

ToDoApp/templates/home.html
{% extends "base.html" %}
{% block title %} Übersicht der Ausgaben {% endblock %}
{% block content %}
<h2> Übersicht aller Monate </h2>
<div class="container m-0 p-0">
    <div class="row row-cols-4 g-2">
        <div class="column">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title"> Januar </h1>
                    <p>
                        <a href="{% url 'ToDoApp:ausgaben' 1%}">Januar</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="column">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title"> Februar </h1>
                    <p>
                        <a href="{% url 'ToDoApp:ausgaben' 2%}">Februar</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="column">
             <div class="card">
                <div class="card-body">
                    <h1 class="card-title"> März </h1>
                    <p>
                        <a href="{% url 'ToDoApp:ausgaben' 3%}">März</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="column">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title"> April </h1>
                    <p>
                        <a href="{% url 'ToDoApp:ausgaben' 4%}">April</a>
                    </p>
                </div>
            </div>
        </div>         
        <div class="column">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title"> Mai </h1>
                    <p>
                         <a href="{% url 'ToDoApp:ausgaben' 5%}">Mai</a>
                    </p>
                </div>
            </div>
        </div> 
        <div class="column">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title"> Juni </h1>
                    <p>
                        <a href="{% url 'ToDoApp:ausgaben' 6%}">Juni</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="column">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title"> Juli </h1>
                    <p>
                        <a href="{% url 'ToDoApp:ausgaben' 7%}">Juni</a>
                    </p>
                </div>
            </div>
         </div>
         <div class="column">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title"> August </h1>
                    <p>
                        <a href="{% url 'ToDoApp:ausgaben' 8%}">Juni</a>
                    </p>
                </div>
            </div>
         </div>
         <div class="column">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title"> September </h1>
                    <p>
                        <a href="{% url 'ToDoApp:ausgaben' 9%}">Juni</a>
                    </p>
                </div>
            </div>
         </div>
         <div class="column">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title"> Oktober </h1>
                    <p>
                        <a href="{% url 'ToDoApp:ausgaben' 10%}">Juni</a>
                    </p>
                </div>
            </div>
         </div>
         <div class="column">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title"> November </h1>
                    <p>
                        <a href="{% url 'ToDoApp:ausgaben' 11%}">Juni</a>
                    </p>
                </div>
            </div>
         </div>
         <div class="column">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title"> Dezember </h1>
                    <p>
                        <a href="{% url 'ToDoApp:ausgaben' 12%}">Juni</a>
                    </p>
                </div>
            </div>
         </div>
    </div>
</div>
<div class="d-flex justify-content-center">
    {{ div| safe }}
</div>
{% endblock %}
{% block footer %}
<footer class="d-flex justify-content-center">
    <a href="{% url 'admin:index' %}" class="btn btn-warning"> Admin Portal! </a>
</footer>
{{ script| safe }}
{% endblock %}

ToDoApp/templates/save.html
{% for field in form %}
    <td>{{ field }}</td>
{% endfor %}
<td><button type="submit" class="btn btn-primary" name="save" value="{{ ausgabe.id }}">Speichern</button></td>